AWSTemplateFormatVersion: '2010-09-09'
Description: "flows gvision"
Parameters:
  GoogleApiKey:
    Type: String
Resources:
  gettextFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: gettext
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
      Environment:
        Variables:
          GoogleApiKey:
            Ref: GoogleApiKey
  gettextLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: gettextFunction
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ gettextFunction , Arn ]
Outputs:
  gettextFunction:
    Description: 'gettext'
    Value:
      Fn::GetAtt: [ gettextFunction , Arn ]
  gettextRole:
    Description: 'gettext'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
